### ISSUE TITLE
Table Creator

### ISSUE THREAD

**Issue by czgu** [pinterest/querybook#405]
Add the ability to create tables in metastore. The data used to create tables can come from 2 sources:
- User-uploaded CSV file (or other formats?)
- Query Results in CSV format

For user uploaded, provide an upload icon near the search bar. If the environment has a metastore that can be uploaded, then show the export result to the table as an option.

**Comment by SinghAsDev** [comment]
SQL dialects allow creating tables very easily using `create table as` or `create table like` statements. What's the benefit of this approach?

**Comment by czgu** [comment]
@SinghAsDev the main benefit for this is that we can create table based on the input data, the secondary benefit is that you don't need to check the syntax

**Comment by SinghAsDev** [comment]
I see, do you also think that it comes at cost of performance and
efficiency? It would also increase the footprint of text format data, which
is not performant for analytical queries.

Another approach would be to just add a create table wrapper on top of
query with a button, instead of users writing it. I am still not sure if
that would be really helpful for users, but it would at least be performant
and efficient.
