### ISSUE TITLE
Necessary environment variable for configuring s3 as result storage

### ISSUE THREAD

**Issue by yongchand** [pinterest/querybook#578]
In order to configure S3 as a result storage, **AWS_ACCESS_KEY_ID** and **AWS_SECRET_ACCESS_KEY** are required as environment variable for boto3.
Even though people who are familiar with boto3 may know this fact, I feel like a lot of people will be confused and face "access denied" issue.
Isn't it better to explicitly write this on code or at least on the document?
I am willing to contribute to this :)
Thank you 👍

**Comment by czgu** [comment]
Hi Yongchan, yes that would make sense. When I implemented it internally, the aws_access_key_id and secret key wasn't needed. I was guessing it is because of the iamrole which granted the access.

Would you mind to update the documentation here https://github.com/pinterest/querybook/blob/master/docs_website/docs/integrations/add_result_store.md about the s3 result storage? We can have the format similar to https://github.com/pinterest/querybook/blob/master/docs_website/docs/integrations/add_auth.md. If it is a common problem people face, we can add this to code to make it easier. Thank you!
