### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by WenLongSun19** [pinterest/querybook#605]
I'm trying to get oauth set up with keycloak as backend. So far we've gotten to the point of redirect to keycloak login ui, but even with correct credentials we still get "Unauthorized - The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required." error. 

Context
1. Going to querybook website
2. Getting redirected to keyclock login ui
3. Login
4. Redirected back to querybook
5. See Unauthorized error

**Comment by WenLongSun19** [comment]
Just a bit of more context here - after the redirect back to querybook (where callback happens), we discover that login_user function doesn't get called. We tried logging using a new user and see if it creates a new user in the DB - it didn't. Could it be something wrong with creating sessions or during the callback? （已编辑）

**Comment by czgu** [comment]
Hey @WenLongSun19 it is most likely due to the profile fetching part since the user profile information provided by different identity provider is very different.

To debug this, can you share the server logs here? If you know the shape of the profile JSON, you can override the method in OAuthLoginManager which is required to return a tuple of [Username, User email (can be empty)]
```
    def _parse_user_profile(self, resp):
        user = resp.json()
        username = user["email"].split("@")[0]
        return username, user["email"]
```

**Comment by connorwang** [comment]
OK - so we've nailed the problem. Since we use Keycloak so getting user_profile with token as request params doesn't work (hes to be auth header). We copied code from okta_auth.py and made a little modification now everything works fine.
